theme = "onedark"

[editor]
mouse = false
shell = ["fish", "-c"]
bufferline = "multiple"
color-modes = true
text-width = 120

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# https://docs.helix-editor.com/keymap.html
# https://docs.helix-editor.com/commands.html
# https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
[keys.normal]
C-r = ":config-reload"
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"] # Select the whole line
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "delete_selection"]
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]

A-up = ["goto_line_start", "extend_to_line_end_newline", "yank", "delete_selection", "move_line_up", "paste_before"] # Move the whole line up
A-down = ["goto_line_start", "extend_to_line_end_newline", "yank", "delete_selection", "move_line_down", "paste_before"] # Move the whole line down

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
t = ["extend_till_char"]
s = ["surround_delete"]

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
up = ["extend_line_up", "extend_to_line_bounds"]
down = ["extend_line_down", "extend_to_line_bounds"]
A-up = ["yank", "delete_selection", "move_line_up", "paste_before"] # Move the whole line up
A-down = ["yank", "delete_selection", "move_line_down", "paste_before"] # Move the whole line down
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal.space]
f = "file_picker_in_current_buffer_directory"
F = "file_picker"

# buffer keymaps : b-*
[keys.normal.b]
d = ":buffer-close!"
n = "goto_next_buffer"
p = "goto_previous_buffer"